### ISSUE TITLE
Sha256sum sample

### ISSUE THREAD

**Issue by petikvx** [PaulDotSH/ChillRansomware#1]
Hello

Can you please just give me the sha256sum of the sample plz ?

Thx

**Comment by PaulDotSH** [comment]
I don't understand what you are asking, please be a little bit more clear @petikvx

**Comment by petikvx** [comment]
Hello

Do you have the bin of the ransomware ?

Thx

**Comment by PaulDotSH** [comment]
> Hello
> 
> Do you have the bin of the ransomware ?
> 
> Thx

compile it yourself, you need to change the settings anyway
